#!/usr/bin/env node
/**
 * Commonweave Agent: Synthesizer
 *
 * Framework quality. Runs weekly (Sat 02:00 CT).
 *
 * Checks whether the framework docs (README, RESEARCH.md, DEEP-DIVE.md)
 * make claims the directory data actually supports. Flags unsupported
 * claims so the docs stay honest. Proposes improvements when data is
 * strong enough.
 *
 * Rules:
 *   - Only PROPOSES changes, never writes to framework docs directly
 *   - Each proposal must cite a specific data signal (org count, gap, source)
 *   - Skips areas with insufficient data (<100 orgs) - can't make claims yet
 *   - Archives proposals so the Coordinator can track adoption rate
 *
 * Reads: cartographer report, DB stats
 * Writes: synthesizer-report.json, proposals append to trim_audit/proposals-YYYY-MM-DD.md
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { getStats } = require('./shared/db-utils');
const { writeReport, readReport } = require('./shared/report-writer');
const { loadPriorityContext } = require('./shared/priority-context');

const RESEARCH_PATH = path.resolve(__dirname, '../RESEARCH.md');
const PROPOSALS_DIR = path.resolve(__dirname, '../data/trim_audit');

// Framework areas and their minimum evidence thresholds
const AREA_THRESHOLDS = {
  democratic_sovereignty: { min: 500, claim_level: 'strong' },
  universal_sufficiency: { min: 500, claim_level: 'strong' },
  ecological_equilibrium: { min: 200, claim_level: 'moderate' },
  economic_democracy: { min: 100, claim_level: 'moderate' },
  healthcare: { min: 100, claim_level: 'moderate' },
  education: { min: 100, claim_level: 'moderate' },
  food: { min: 100, claim_level: 'moderate' },
  housing_land: { min: 50, claim_level: 'light' },
  energy_digital: { min: 50, claim_level: 'light' },
  transparency_by_default: { min: 100, claim_level: 'moderate' },
};

function assessEvidence(area, orgCount) {
  const threshold = AREA_THRESHOLDS[area];
  if (!threshold) return { status: 'unknown_area', confidence: 'none' };
  if (orgCount >= threshold.min * 3) return { status: 'well_supported', confidence: 'high' };
  if (orgCount >= threshold.min) return { status: 'supported', confidence: 'medium' };
  if (orgCount >= threshold.min * 0.3) return { status: 'thin', confidence: 'low' };
  return { status: 'insufficient', confidence: 'none' };
}

function buildProposals(areaAssessments, cartReport) {
  const proposals = [];

  areaAssessments.forEach(({ area, count, assessment }) => {
    if (assessment.status === 'well_supported') {
      proposals.push({
        type: 'strengthen_claim',
        area,
        evidence: `${count} organizations mapped`,
        proposal: `Framework docs for ${area} can cite ${count} mapped organizations as evidence. Consider adding a "what exists now" summary citing the directory.`,
        confidence: assessment.confidence,
        priority: 'low',
      });
    }

    if (assessment.status === 'thin') {
      proposals.push({
        type: 'add_hedge',
        area,
        evidence: `Only ${count} organizations in ${area}`,
        proposal: `Add a hedge to ${area} section: "Coverage is thin - we have ${count} organizations mapped but this is an early sample. Claims in this section are directional."`,
        confidence: assessment.confidence,
        priority: 'medium',
      });
    }

    if (assessment.status === 'insufficient') {
      proposals.push({
        type: 'add_gap_note',
        area,
        evidence: `${count} organizations - below evidence threshold of ${AREA_THRESHOLDS[area]?.min}`,
        proposal: `${area} section should note that directory evidence is insufficient to validate claims. Flag as "needs data" until ${AREA_THRESHOLDS[area]?.min}+ orgs mapped.`,
        confidence: assessment.confidence,
        priority: 'high',
      });
    }
  });

  // Gap-specific proposals from Cartographer
  if (cartReport?.top_priority_gaps?.length > 0) {
    const criticalCountries = cartReport.top_priority_gaps.slice(0, 5).map(g => g.country_code).join(', ');
    proposals.push({
      type: 'coverage_note',
      area: 'global',
      evidence: `${cartReport.top_priority_gaps.length} countries critically underrepresented`,
      proposal: `Add a coverage limitations section to README: "Current coverage is strongest in North America/Europe and weakest in [${criticalCountries}]. We are actively seeking regional contributors for these areas."`,
      confidence: 'high',
      priority: 'high',
    });
  }

  return proposals;
}

function writeProposalsFile(proposals) {
  fs.mkdirSync(PROPOSALS_DIR, { recursive: true });
  const today = new Date().toISOString().slice(0, 10);
  const outPath = path.join(PROPOSALS_DIR, `proposals-${today}.md`);

  const lines = [
    `# Synthesizer Proposals - ${today}`,
    '',
    `Generated by Synthesizer agent. These are PROPOSALS for Simon to review, not auto-applied changes.`,
    '',
    `## Summary`,
    `Total proposals: ${proposals.length}`,
    `High priority: ${proposals.filter(p => p.priority === 'high').length}`,
    `Medium priority: ${proposals.filter(p => p.priority === 'medium').length}`,
    '',
    '## Proposals',
    '',
  ];

  proposals.forEach((p, i) => {
    lines.push(`### ${i + 1}. [${p.priority.toUpperCase()}] ${p.type} - ${p.area}`);
    lines.push(`**Evidence:** ${p.evidence}`);
    lines.push(`**Confidence:** ${p.confidence}`);
    lines.push(`**Proposal:** ${p.proposal}`);
    lines.push('');
  });

  fs.writeFileSync(outPath, lines.join('\n'));
  return outPath;
}

async function run() {
  const ctx = loadPriorityContext('synthesizer');
  const cartReport = readReport('cartographer');
  const stats = getStats();

  // Build area assessment from DB counts
  const areaMap = {};
  stats.byArea.forEach(({ framework_area, n }) => {
    if (framework_area) areaMap[framework_area] = (areaMap[framework_area] || 0) + n;
  });

  const areaAssessments = Object.entries(AREA_THRESHOLDS).map(([area]) => ({
    area,
    count: areaMap[area] || 0,
    assessment: assessEvidence(area, areaMap[area] || 0),
  }));

  const proposals = buildProposals(areaAssessments, cartReport);
  const proposalsPath = writeProposalsFile(proposals);

  // Research.md freshness check
  let researchAge = null;
  if (fs.existsSync(RESEARCH_PATH)) {
    const stat = fs.statSync(RESEARCH_PATH);
    researchAge = Math.floor((Date.now() - stat.mtimeMs) / (1000 * 60 * 60 * 24));
  }

  const report = {
    run_at: new Date().toISOString(),
    version: '1.0',
    area_assessments: areaAssessments,
    proposals_count: proposals.length,
    proposals_by_priority: {
      high: proposals.filter(p => p.priority === 'high').length,
      medium: proposals.filter(p => p.priority === 'medium').length,
      low: proposals.filter(p => p.priority === 'low').length,
    },
    proposals_file: proposalsPath,
    research_md_age_days: researchAge,
    overall_framework_quality: areaAssessments.filter(a => a.assessment.status === 'well_supported').length,
    areas_needing_hedges: areaAssessments.filter(a => a.assessment.status === 'thin' || a.assessment.status === 'insufficient').map(a => a.area),
    coordinator_context_used: ctx.available,
    cartographer_input_used: !!cartReport,
  };

  const outPath = writeReport('synthesizer', report);
  console.log(`[synthesizer] Done. ${proposals.length} proposals written to ${proposalsPath}`);
  console.log(`[synthesizer] Report: ${outPath}`);
}

run().catch(e => { console.error('[synthesizer] ERROR:', e.message); process.exit(1); });
